### ISSUE TITLE
Integrate React

### ISSUE THREAD

**Issue by aryanbaburajan** [DucktapeEngine/ducktapeengine.github.io#5]
Through https://reactjs.org/docs/add-react-to-a-website.html, as a script tag.

And as for the page `index.html`,
- For now, render a "Hello world!" through React components
- But also, do not disable the redirection

**Comment by YeffyCodeGit** [comment]
Could I tackle this issue?

**Comment by aryanbaburajan** [comment]
@YeffyCodeGit No
